### ISSUE TITLE
USDT

### ISSUE THREAD

**Issue by RasyidMMJ** [RasyidMMJ/USDT#2]
CAN"T NOT TRANSACTION TRUSTWALLET "SEND", "RECEIVE", "BUY", "SELL"
USDT "463,804.881338" ADDRESS "0x84811d901063391658ddaCb6Dbc6926d9014038D"

**Comment by UserGithub005** [comment]
Hallo RasyidMMJ,,,, 
Please update your address wallet. 

~Bookish space palm-tree

**Comment by RasyidMMJ** [comment]
0x26988c5054ff1e2c37cf0874963c7da23f4415e8
